name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tmate_enabled:
        description: 'Enable remote shell'
        required: true
        default: false
      CACHE_KEY:
        description: 'Cache to retrieve'
        default: '1234'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  interactive:
    runs-on: ubuntu-latest
    steps:
       - name: Interactive Session
         uses: mxschmitt/action-tmate@v3
         if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate_enabled }}
         timeout-minutes: 5
         with:
          install-dependencies: true

  # XXX This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: env
        run: |
          Add-Content $env:GITHUB_ENV LOCALAPPDATA=$env:LOCALAPPDATA

      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ${{ env.LOCALAPPDATA }}/vcpkg/archives
          # An explicit key for restoring and saving the cache
          key: ${{ github.event.inputs.CACHE_KEY }}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          #restore-keys: # optional
          # The chunk size used to split up large files during upload, in bytes
          #upload-chunk-size: # optional

      - name: cmake
        run: cmake --preset x64-debug
